language: java
jdk:
  - oraclejdk8
install: true
before_script:
  - ln -s "$(pwd)/calico-ng/src/calico" "$(pwd)/web/src/calico"
script:
  - ./gradlew clean build --info
deploy:
  - provider: script
    script: ./gradlew bintrayUpload
    on:
      tags: true
