language: java
jdk:
  - openjdk8
install: true
script:
  - ./gradlew clean
  - ./gradlew calico-core:build calico-fmmail:build calico-jackson:build calico-servlet:build --info
deploy:
  - provider: script
    script: ./gradlew bintrayUpload
    on:
      tags: true
