version: '3'
services:
  db:
    image: postgres:11.1-alpine
    restart: always
    environment:
      POSTGRES_USER: calico-sample
      POSTGRES_PASSWORD: ''
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
      TZ: Asia/Tokyo
    ports:
      - "5432:5432"
